<template lang="pug">
    v-layout#login(align-center justify-center)
        v-card(mx-auto min-width="460")
            //- h1(style="text-align: center" display-1 text--primary) Sign in iRouteCDN 
            v-img.mx-auto.signIn(:src="require('../assets/images/iRouteCDN_signin.png')" max-width="160")
            v-window(v-model="step")
                v-window-item(:value="1")
                    v-form(ref="userForm" lazy-validation valid onsubmit="return false;")
                        v-container
                            v-text-field(v-model="user.unique_id" label="Client Id" type="text" name="unique_id" :rules="[rules.required]")
                            v-text-field(v-model="user.email" label="Email" type="text" name="email" :rules="[rules.required, rules.email]")
                            v-text-field(v-model="user.password" label="Password" name="password" :append-icon="passwordShow ? 'visibility' : 'visibility_off'" :type="passwordShow ? 'text' : 'password'" @click:append="passwordShow = !passwordShow" :rules="[rules.required]" @keyup.native.enter="signIn")
                            v-alert.text-md-left(:value="loginError" color="error" icon="warning" outline transition="scale-transition") {{loginErrorMessage}}
                            //- v-checkbox(label="Remember me" color="primary")
                            v-btn(color="primary" block @click="signIn") Sign in
                            router-link(to="/forgot") Forgot your password?
                v-window-item(:value="2")
                    v-form(ref="otpForm" lazy-validation valid onsubmit="return false;")
                        v-container
                            .tips.text-md-left Enter the code generated by your authenticator app.
                            v-text-field(v-model="otpCode" label="6-digit security code" mask="######" type="text" name="otpcode" :rules="[rules.required, rules.otp]" @keyup.native.enter="checkOTPCode")
                            v-alert.text-md-left(:value="otpError" color="error" icon="warning" outline transition="scale-transition") Invalid code
                            v-btn.mt-3(color="primary" block @click="checkOTPCode") Enter

        v-snackbar(v-model="$store.state.global.snackbar.status" :color="$store.state.global.snackbar.color" :timeout="$store.state.global.snackbar.timeout" top ) {{$store.state.global.snackbar.text}}
            v-btn(dark flat @click="$store.dispatch('global/closeSnackbar')") CLOSE

</template>

<script>
import Loading from "../components/Loading";

export default {
    components: {
        Loading
    },
    data() {
        return {
            permission: [],
            passwordShow: false,
            step: 1,
            rules: {
                required: value => !!value || "Required.",
                email: value => {
                    const pattern = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
                    return pattern.test(value) || "Invalid e-mail.";
                },
                otp: value =>
                    (value != null && value.length == 6) ||
                    "Please enter 6-digit code."
            },
            otpCode: "",
            otpToken: "",
            user: { email: "", password: "", key: "" },
            loginError: false,
            loginErrorMessage: "",
            otpError: false
        };
    },
    methods: {
        signIn: function() {
            this.loginError = false;
            if (this.$refs.userForm.validate()) {
                this.$store.dispatch("global/startLoading");
                this.$store
                    .dispatch("account/login", this.user)
                    .then(
                        (result => {
                            this.getSelfPermission();
                            if (result.data.google2fa) {
                                this.step = 2;
                                this.otpToken = result.data.token;
                            } else {
                                this.loginSuccess();
                            }
                            this.$store.dispatch("global/finishLoading");
                        }).bind(this)
                    )
                    .catch(
                        (error => {
                            this.loginErrorMessage = error.message;
                            this.loginError = true;
                            this.$store.dispatch("global/finishLoading");
                        }).bind(this)
                    );
            }
        },
        getSelfPermission: function() {
            this.$store
                .dispatch("permission/getSelfPermission")
                .then(
                    function(result) {
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        checkOTPCode: function() {
            if (this.$refs.otpForm.validate()) {
                this.$store.dispatch("global/startLoading");
                this.$store
                    .dispatch("account/verify2FACode", {
                        "verify-code": this.otpCode,
                        token: this.otpToken
                    })
                    .then(
                        function(result) {
                            this.loginSuccess();
                            this.$store.dispatch("global/finishLoading");
                        }.bind(this)
                    )
                    .catch(
                        function(error) {
                            this.otpError = true;
                            this.$store.dispatch("global/finishLoading");
                        }.bind(this)
                    );
            }
        },
        loginSuccess: function() {
            this.$router.push("/admin/");
            // var redirect = this.$route.query.redirect;
            // if (redirect != null) {
            //     location.replace(redirect + "?token=" + localStorage.getItem("token"));
            // } else {
            //     this.$router.push("/admin/cdn-providers");
            // }
        }
    },
    mounted() {
        var message = this.$route.query.message;
        var type = this.$route.query.type;
        // if (type == "success") {
        //     this.$store.dispatch(
        //         "global/showSnackbarSuccess",
        //         "Sign out success!"
        //     );
        //     // this.showSnackBar(message, type, 10000);
        // }
    },
    created() {
        this.user.key = process.env.VUE_APP_PLATFORM_KEY;
    },
    beforeCreate() {
        console.log(JSON.parse(localStorage.getItem("permission")), "berfor");
    }
};
</script>

<style scoped>
.v-stepper {
    background: transparent;
    box-shadow: none;
}
.signIn {
    margin-top: 40px;
}
</style>