<template lang="pug">
    v-container#user-list.grid-list-lg
        v-layout(wrap)
            v-flex(xs12)
                .title Users
            v-flex(xs12)
                v-card
                    v-card-title
                        .subheading User List
                        v-spacer
                        v-btn.my-0(color="primary" @click="addUser()") Add User
                    v-divider
                    v-card-text
                        v-layout(wrap)
                            v-flex(xs12 sm6 md4)
                                v-text-field(v-model="searchText" append-icon="search" label="Search" single-line hide-details)

                    h7-data-table(:headers="headers" :items="filterData" :loading="$store.state.global.isLoading" :search-text="searchText" single-line :per-page="10")
                        template(slot="items" slot-scope="{props, index}")
                            tr(:class="props.item.status? '': 'grey--text'")
                                td {{index}}
                                td {{props.item.name}}
                                td {{props.item.role.name}}
                                td {{props.item.email}}
                                td {{props.item.last_login_time}}
                                td
                                    v-btn.ma-0(flat icon small color="primary" @click="editUser(props.item)" title="edit" )
                                        v-icon(small) edit
                                    v-menu(offset-y left) 
                                        template(v-slot:activator="{on}")
                                            v-btn.ma-0(flat icon small color="primary" v-on="on")
                                                v-icon( small) more_vert
                                        v-list
                                            v-list-tile(@click="updateUserStatus(props.item, !props.item.status)")
                                                v-list-tile-title(v-if="props.item.status") inactive user
                                                v-list-tile-title(v-else) active user
                                            v-list-tile(@click="resetPassword(props.item)")
                                                v-list-tile-title reset password
            v-dialog.edit-dialog(v-model="dialog" max-width="460" persistent)
                v-card
                    v-card-title.title {{formTitle}}
                    v-card-text
                        v-form(ref="editForm")
                            v-text-field(v-model="userInfo.name" label="Name" type="text" name="name" :rules="[rules.required]")
                            v-text-field(v-model="userInfo.email" label="Email" type="text" name="email" :rules="[rules.required, rules.email]" :disabled="editedIndex === -1 ? false : true")
                            v-text-field(v-model="userInfo.phone" label="Phone" type="text" name="phone")
                            v-select(:items="roleList" item-text="name" item-value="name" @change="chooseRole(userInfo.roleName)" v-model="userInfo.roleName" label="Role")
                            v-radio-group(v-model="userInfo.passwordType")
                                v-radio(key="1"  label="Autogenerated password" value="1")
                                v-radio(key="2"  label="Custom password" value="2")
                            v-text-field(v-if="userInfo.passwordType==2" v-model="userInfo.password" label="Password" type="password" name="password" :rules="[rules.required]")

                    v-card-actions  
                        v-spacer
                        v-btn(color="grey" flat="flat" @click="closeDialog()") Cancel
                        v-btn(color="primary" flat="flat" @click="updateUser()") Save
</template>

<script>
import textFieldRules from "../../utils/textFieldRules";

export default {
    mixins: [textFieldRules],
    data() {
        return {
            userGroupId: "",
            filterData: [],
            rawData: [],
            searchText: "",
            userInfo: {},
            editedIndex: -1,
            headers: [
                {
                    text: "#",
                    align: "left",
                    sortable: false,
                    width: "80px",
                    value: "index"
                },
                {
                    text: "Name",
                    align: "left",
                    sortable: true,
                    value: "name"
                },
                {
                    text: "Role",
                    align: "left",
                    sortable: true,
                    value: "role.name"
                },
                {
                    text: "Email",
                    align: "left",
                    value: "email",
                    sortable: true
                },
                {
                    text: "Last Login Time",
                    align: "left",
                    value: "last_login_time",
                    sortable: true
                },
                {
                    text: "Actions",
                    align: "left",
                    value: "action",
                    sortable: false,
                    width: "150px"
                }
            ],
            dialog: false,
            roleList: [],
            roleMapping: {},
            chooseRoleId: ""
        };
    },
    methods: {
        getAllUsers: function() {
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("users/getAll")
                .then(
                    function(result) {
                        this.rawData = result.data;
                        this.filterData = this.rawData;
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        getUsersByGroupId() {
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("users/getUsersByGroup", this.userGroupId)
                .then(
                    function(result) {
                        this.rawData = result.data;
                        this.filterData = this.rawData;
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        getRolesByGroupId() {
            // console.log(this.roleList);
            // this.items = this.roleList;
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("roles/getRolesByGroupId", this.userGroupId)
                .then(
                    function(result) {
                        this.roleList = result.data;
                        this.roleList.forEach((o, i) => {
                            this.roleMapping[o.name] = o.id;
                        });
                        // console.log(this.roleMapping);
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        chooseRole(value) {
            // console.log(value);
            // console.log(this.roleMapping[value]);
            this.userInfo.chooseRoleId = this.roleMapping[value];
            // console.log(value);
            // console.log(this.userInfo, "userInfo");
            // console.log(this.editedIndex);
        },
        addUser() {
            this.editedIndex = -1;
            this.userInfo = { passwordType: "1" };
            this.dialog = true;
        },
        editUser(item) {
            this.userInfo = Object.assign({}, item);
            // console.log(this.userInfo);
            this.userInfo["roleName"] = item.role.name;
            this.editedIndex = this.filterData.indexOf(item);
            this.dialog = true;
        },
        updateUser: function() {
            if (this.$refs.editForm.validate()) {
                this.$store.dispatch("global/startLoading");
                if (this.editedIndex == -1) {
                    this.addNewUser();
                } else {
                    this.$store
                        .dispatch("users/updateUserProfile", this.userInfo)
                        .then(
                            function(result) {
                                this.updateUserRole();
                                this.$store.dispatch(
                                    "global/showSnackbarSuccess",
                                    "Update user success!"
                                );
                            }.bind(this)
                        )
                        .catch(
                            function(error) {
                                this.$store.dispatch("global/finishLoading");
                                this.$store.dispatch(
                                    "global/showSnackbarError",
                                    error.message
                                );
                                this.closeDialog();
                            }.bind(this)
                        );
                }
            }
        },
        updateUserRole() {
            this.$store
                .dispatch("users/updateUserRole", this.userInfo)
                .then(
                    function(result) {
                        this.$store.dispatch(
                            "global/showSnackbarSuccess",
                            "Update user success!"
                        );
                        this.getUsersByGroupId();
                        this.closeDialog();
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.closeDialog();
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                );
        },
        newUserRole(uid) {
            this.userInfo.uid = uid;
            this.$store
                .dispatch("users/newUserRole", this.userInfo)
                .then(
                    function(result) {
                        this.$store.dispatch(
                            "global/showSnackbarSuccess",
                            "Update user success!"
                        );
                        this.getUsersByGroupId();
                        this.closeDialog();
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.closeDialog();
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                );
        },
        addNewUser: function() {
            // console.log("NEW");
            this.$store
                .dispatch("users/newUser", this.userInfo)
                .then(
                    function(result) {
                        this.newUserRole(result.data.uid);
                        // this.$store.dispatch(
                        //     "global/showSnackbarSuccess",
                        //     "Update user success!"
                        // );
                        // this.getUsersByGroupId();
                        // this.closeDialog();
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.closeDialog();
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                );
        },
        updateUserStatus: function(item, status) {
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("users/updateUserStatus", {
                    uid: item.uid,
                    status: status
                })
                .then(
                    function(result) {
                        // this.getAllUsers();
                        this.getUsersByGroupId();
                        this.closeDialog();
                        this.$store.dispatch(
                            "global/showSnackbarSuccess",
                            "Update status success!"
                        );
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                        this.$store.dispatch("global/finishLoading");
                        this.closeDialog();
                    }.bind(this)
                );
        },
        resetPassword(user) {
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("users/forgotPassword", user.email)
                .then(
                    function(result) {
                        this.$store.dispatch(
                            "global/showSnackbarSuccess",
                            "An e-mail will be sent to " +
                                user.email +
                                " with further instructions."
                        );
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                );
        },
        closeDialog() {
            this.dialog = false;
            this.$refs.editForm.reset();
        }
    },
    computed: {
        formTitle() {
            if (this.editedIndex === -1) return "Add User";
            else return "Edit User";
        }
    },
    created() {
        this.userGroupId = this.$store.getters["account/accountGroupId"]();
        // console.log(this.userGroupId);
        this.getUsersByGroupId();
        this.getRolesByGroupId();
    }
};
</script>

<style lang="scss" scoped>
</style>