<template lang="pug">
    v-container#user-list(grid-list-lg)
        v-layout(wrap)
            v-flex(xs12)
                .title {{groupInfo.name}}
            v-flex(xs12)
                v-breadcrumbs.pa-0(:items="breadcrumbsItems")
            v-flex(xs12)
                v-card
                    v-card-title 
                        .subheading Information
                        v-spacer
                        v-btn.my-0(color="primary" @click="editGroup()") Edit
                    v-divider
                    v-card-text
                        v-layout(wrap row)
                            v-flex(sm5 md2)
                                .text.font-weight-bold Name
                            v-flex(sm5 md10)
                                .text {{groupInfo.name }}
                            v-flex(sm5 md2)
                                .text.font-weight-bold Client ID
                            v-flex(sm5 md10)
                                .text {{groupInfo.unique_id }}
            v-flex(xs12)
                v-card
                    v-card-title
                        .subheading Users
                        v-spacer
                        v-btn.my-0(color="primary" @click="addUser()") Add User
                    v-divider
                    v-card-text
                        v-layout(wrap)
                            v-flex(xs12 sm6 md4)
                                v-text-field(v-model="searchText" append-icon="search" label="Search" single-line hide-details)

                    h7-data-table(:headers="headers" :items="filterData" :loading="$store.state.global.isLoading" :search-text="searchText" :per-page="10" single-line)
                        template(slot="items" slot-scope="{props, index}")
                            td {{index}}
                            td {{props.item.name}}
                            td {{props.item.role.name}}
                            td {{props.item.email}}
                            td {{props.item.last_login_time}}
                            td
                                v-btn.ma-0(flat icon small color="primary" @click="editUser(props.item)" title="edit" )
                                    v-icon(small) edit
                                v-btn.ma-0(flat icon small color="primary" @click="removeUser(props.item)" title="delete" )
                                    v-icon(small) delete

            //- edit group dialog
            v-dialog(v-model="dialog.edit" max-width="460" persistent)
                v-card
                    v-card-title.title Edit Group
                    v-card-text
                        v-form(ref="editForm")
                            v-text-field(v-model="editedGroup.name" label="Name")
                            v-text-field(v-model="editedGroup.unique_id" label="Client ID")
                    v-card-actions
                        v-spacer
                        v-btn(color="grey" flat @click="closeDialog()") CANCEL
                        v-btn(color="primary" flat @click="updateGroup()") SAVE

            v-dialog(v-model="dialog.addUser" max-width="460" scrollable persistent)
                v-card
                    v-window(v-model="addingStep")
                        v-window-item(:value="1")
                            v-card-title.title Add User
                            v-card-text
                                v-form(ref="addEmailForm")
                                    v-text-field(v-model="userInfo.email" label="Email" :rules="[rules.required, rules.email]")
                            v-card-actions  
                                v-spacer
                                v-btn(color="grey" flat @click="closeDialog()") Cancel
                                v-btn(color="primary" flat @click="nextStep()") Next
                        v-window-item(:value="2")
                            v-card-title.title {{formTitle}}
                            v-card-text
                                .text.mb-2 Are you sure you want to add following user in {{groupInfo.name}} ?
                                v-form(ref="addUserForm")
                                    v-text-field(v-model="userInfo.name" label="Name" :rules="[rules.required]" :readonly="isReadOnly")
                                    v-text-field(v-model="userInfo.email" label="Email" :rules="[rules.required]" readonly)
                                    v-select(v-model="userInfo.roleName" :items="roleList" item-text="name" item-value="name" label="Role" @change="chooseRole(userInfo.roleName)" :rules="[rules.required]")
                                    v-radio-group(v-model="userInfo.passwordType" v-if="type == 'NewUser'")
                                        v-radio(key="1"  label="Autogenerated password" value="1")
                                        v-radio(key="2"  label="Custom password" value="2")
                                    v-text-field(v-if="userInfo.passwordType == 2" v-model="userInfo.password" label="Password" type="password" name="password" :rules="[rules.required]")
                            v-card-actions
                                v-btn(color="primary" flat="flat" @click="backAction()") Back  
                                v-spacer
                                v-btn(color="grey" flat="flat" @click="closeDialog()") Cancel
                                v-btn(color="primary" flat="flat" @click="addUserAction()") YES
            //- edit user dialog
            v-dialog(v-model="dialog.editUser" max-width="460" persistent)
                    v-card
                        v-card-title.title Edit user
                        v-card-text
                            v-form(ref="editForm")
                                v-text-field(v-model="userInfo.name" label="Name" :rules="[rules.required]" readonly)
                                v-select(v-model="userInfo.roleName" :items="roleList" item-text="name" item-value="name" label="Role" @change="chooseRole(userInfo.roleName)" :rules="[rules.required]")
                        v-card-actions
                            v-spacer
                            v-btn(color="grey" flat="flat" @click="closeDialog()") Cancel
                            v-btn(color="primary" flat="flat" @click="updateUserRole()") Save
            //- remove user dialog
            v-dialog(v-model="dialog.removeUser" max-width="460")
                v-card
                    v-card-title.title Remove user from group
                    v-card-text
                        .text Are you sure you want to remove {{userInfo.name}} ({{userInfo.email}}) from {{groupInfo.name}}?
                    v-card-actions
                        v-spacer
                        v-btn(color="error" flat @click="removeUserFromGroup()") Remove
                        v-btn(color="grey" flat @click="closeDialog()") CANCEL
</template>

<script>
import textFieldRules from "../../utils/textFieldRules";

export default {
    mixins: [textFieldRules],
    props: {
        info: {
            type: Object,
            default: function() {
                return {};
            }
        }
    },
    data() {
        return {
            groupId: 0,
            breadcrumbsItems: [
                {
                    text: "Groups",
                    disabled: false,
                    exact: true,
                    to: "/admin/user-groups"
                },
                {
                    text: "",
                    disabled: true,
                    exact: true,
                    to: ""
                }
            ],
            groupInfo: {},
            editedGroup: {
                id: 1,
                name: "Hiero7",
                unique_id: "Hiero7",
                deleted_at: null
            },
            addingStep: 1,
            userInfo: { email: "", name: "", passwordType: "2" },
            roleItems: [
                { name: "User", value: "2" },
                { name: "Admin", value: "1" }
            ],
            filterData: [],
            rawData: [],
            searchText: "",
            headers: [
                {
                    text: "#",
                    align: "left",
                    sortable: false,
                    width: "80px",
                    value: "index"
                },
                {
                    text: "Name",
                    align: "left",
                    sortable: true,
                    value: "name"
                },
                {
                    text: "Role",
                    align: "left",
                    sortable: true,
                    value: "role"
                },
                {
                    text: "Email",
                    align: "left",
                    value: "email",
                    sortable: true
                },
                {
                    text: "Last Login Time",
                    align: "left",
                    value: "last_login_time",
                    sortable: true
                },
                {
                    text: "Actions",
                    align: "left",
                    value: "action",
                    sortable: false,
                    width: "150px"
                }
            ],
            dialog: {
                edit: false,
                addUser: false,
                editUser: false,
                removeUser: false
            },
            users: [],
            type: "",
            isReadOnly: true,
            roleList: [],
            roleMapping: {}
        };
    },
    computed: {
        formTitle() {
            return this.type === "NewUser" ? "New User" : "Exist User";
        }
    },
    methods: {
        chooseRole(value) {
            // console.log(value);
            this.userInfo.chooseRoleId = this.roleMapping[value];
            // console.log(this.userInfo);
        },
        getGroupInfo() {
            // this.groupInfo = { id: 1, name: "Hiero7 Test!!!!", unique_id: "Hiero7 Test!!!!", deleted_at: null };
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("userGroup/getById", this.groupId)
                .then(
                    function(result) {
                        this.groupInfo = result.data;
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        getGroupUserInfo() {
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("users/getUsersByGroup", this.groupId)
                .then(
                    function(result) {
                        this.filterData = result.data;
                        // console.log(this.filterData);
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        getRolesByGroupId() {
            // console.log(this.roleList);
            // this.items = this.roleList;
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("roles/getRolesByGroupId", this.groupId)
                .then(
                    function(result) {
                        this.roleList = result.data;
                        this.roleList.forEach((o, i) => {
                            this.roleMapping[o.name] = o.id;
                        });
                        // console.log(this.roleList);
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        findUserByEmail: function(email) {
            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("users/getAll")
                .then(
                    function(result) {
                        this.users = result.data;
                        this.users.find(item => {
                            if (item.email == email) {
                                this.userInfo = item;
                            }
                        });
                        if (this.userInfo.uid !== undefined) {
                            this.type = "ExistUser";
                            this.isReadOnly = true;
                        } else {
                            this.type = "NewUser";
                            this.isReadOnly = false;
                        }
                        this.addingStep = 2;
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            "Please enter exist user's email."
                        );
                    }.bind(this)
                );
        },
        nextStep() {
            switch (this.addingStep) {
                case 1:
                    if (this.$refs.addEmailForm.validate()) {
                        this.findUserByEmail(this.userInfo.email);
                    }
                    break;

                default:
                    break;
            }
        },
        editGroup() {
            this.editedGroup = Object.assign({}, this.groupInfo);
            this.dialog.edit = true;
        },
        addUser() {
            this.dialog.addUser = true;
            this.userInfo.passwordType = "2";
        },
        editUser(data) {
            // console.log(data);
            this.userInfo = Object.assign({}, data);
            this.userInfo["roleName"] = this.userInfo.role.name;
            this.dialog.editUser = true;
            // console.log(this.userInfo);
        },
        removeUser(data) {
            this.userInfo = Object.assign({}, data);
            this.dialog.removeUser = true;
        },
        updateUserRole() {
            this.$store
                .dispatch("users/updateUserRole", this.userInfo)
                .then(
                    function(result) {
                        this.$store.dispatch(
                            "global/showSnackbarSuccess",
                            "Update user success!"
                        );
                        this.getGroupUserInfo();
                        this.closeDialog();
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.closeDialog();
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                );
        },
        addUserAction() {
            this.userInfo.groupId = this.groupId;
            if (this.type == "ExistUser") {
                this.updateUserRole();
            } else {
                this.addNewUser();
            }
            // console.log(this.userInfo);
        },
        addNewUser: function() {
            var userInfo = {};
            userInfo.name = this.userInfo.name;
            userInfo.email = this.userInfo.email;
            userInfo.passwordType = "2";
            this.$store
                .dispatch("users/newUser", userInfo)
                .then(
                    function(result) {
                        this.userInfo.uid = result.data.uid;
                        this.updateUserRole();
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                );
        },
        removeUserFromGroup() {
            this.userInfo.groupId = this.groupId;

            this.$store.dispatch("global/startLoading");
            this.$store
                .dispatch("userGroup/removeUserFromGroup", this.userInfo)
                .then(
                    function(result) {
                        this.getGroupUserInfo();
                        this.$store.dispatch(
                            "global/showSnackbarSuccess",
                            "Remove user from group success!"
                        );
                        this.closeDialog();
                        this.$store.dispatch("global/finishLoading");
                    }.bind(this)
                )
                .catch(
                    function(error) {
                        this.$store.dispatch("global/finishLoading");
                        this.$store.dispatch(
                            "global/showSnackbarError",
                            error.message
                        );
                    }.bind(this)
                );
        },
        updateGroup() {
            if (this.$refs.editForm.validate()) {
                this.$store.dispatch("global/startLoading");
                this.$store
                    .dispatch("userGroup/updateUserGroup", this.editedGroup)
                    .then(
                        function(result) {
                            this.$store.dispatch("global/finishLoading");
                            this.getGroupInfo();
                            this.closeDialog();
                        }.bind(this)
                    )
                    .catch(
                        function(error) {
                            this.$store.dispatch("global/finishLoading");
                            this.$store.dispatch(
                                "global/showSnackbarError",
                                error.message
                            );
                            this.closeDialog();
                        }.bind(this)
                    );
            }
        },
        backAction() {
            this.addingStep = 1;
            this.$refs.editForm.reset();
            this.$refs.addEmailForm.reset();
            this.$refs.addUserForm.reset();
            this.userInfo = {};
        },
        closeDialog() {
            this.dialog.edit = false;
            this.dialog.addUser = false;
            this.dialog.editUser = false;
            this.dialog.removeUser = false;
            this.addingStep = 1;
            this.$refs.editForm.reset();
            this.$refs.addEmailForm.reset();
            this.$refs.addUserForm.reset();
        }
    },
    watch: {
        groupInfo: function() {
            this.breadcrumbsItems[
                this.breadcrumbsItems.length - 1
            ].text = this.groupInfo.name;
        }
    },

    mounted() {
        this.breadcrumbsItems[
            this.breadcrumbsItems.length - 1
        ].text = this.groupInfo.name;
    },
    created() {
        this.groupId = this.$route.params.group_id;
        if (this.info.id != null) {
            this.groupInfo = this.info;
        } else {
            this.getGroupInfo();
        }
        this.getGroupUserInfo();
        this.getRolesByGroupId();
    }
};
</script>

<style lang="scss" scoped>
</style>